### ISSUE TITLE
咨询一下是怎么处理 bpftrace -e ’PROGRAM‘ 用法

### ISSUE THREAD

**Issue by cntianci** [XinShuichen/sopacker#2]
sopacker 生成的是一个脚本，如果打包的对象是 bpftrace，生成的程序假如是 `bpftrace_pack`
一般使用 bpftrace 的用法是 `bpftrace -e 'kprobe:xxx {}'`，如果直接使用 `bpftrace_pack -e 'kprobe:xxx {}'`，那么 `bpftrace_pack` 会直接处理掉 `-e` 参数，无法通过 `$@` 传递给 `bpftrace`。

**Comment by XinShuichen** [comment]
你是用的最新的吗 最新已经改了这个问题  https://github.com/XinShuichen/sopacker/commit/6758a37fbdad3ed14713d5931d59c134ac5aa218

**Comment by cntianci** [comment]
用的旧代码，新的是ok的，感谢
